server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myw?serverTimezone=UTC
    username: root
    password:
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:config/config.xml
  type-aliases-package: com.example.demo.dao.entity